language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 7.0
  - 5.6
  - 5.5

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then rm composer.lock; composer require --no-update "phpunit/php-code-coverage:~2"; fi'
  - composer install -n --prefer-source

script: "./robo test --coverage"

after_success:
  - travis_retry php vendor/bin/coveralls -v
